version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: tcc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-your_redis_password}
    networks:
      - tcc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: tcc-redis-commander
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-your_redis_password}
    networks:
      - tcc-network
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  tcc-network:
    driver: bridge
